// js/knowledge-data.js - Data for the Knowledge Graph
// This data structure is the master source of truth, mapping the entire due diligence process
// from raw input documents to the final investment committee presentation.
// It is programmatically generated based on 'Navigator Dataroom Inventory.csv' and 'Navigator DD Flow.csv'.

const knowledgeGraphData = {
    nodes: [
        // --- GROUP 1: INPUT DOCUMENTS (Source: Navigator Dataroom Inventory.csv) ---
        { id: 'DDI-000', label: 'Corporate charter and articles of incorporation', group: 'input_document', description: 'Foundational legal document establishing company structure, purpose, and authorized shares.', location: 'VDR/Corporate & Legal/Corporate Structure & Governance', priority: 'Critical' },
        { id: 'DDI-001', label: 'Bylaws and amendments', group: 'input_document', description: 'Corporate governance rules, procedures, and director/officer powers.', location: 'VDR/Corporate & Legal/Corporate Structure & Governance', priority: 'High Prio' },
        { id: 'DDI-002', label: 'Board of directors meeting minutes (last 3 years)', group: 'input_document', description: 'Record of board decisions, strategic direction, and governance oversight.', location: 'VDR/Corporate & Legal/Corporate Structure & Governance', priority: 'High Prio' },
        { id: 'DDI-003', label: 'Shareholder meeting minutes (last 3 years)', group: 'input_document', description: 'Shareholder voting history and major corporate decisions.', location: 'VDR/Corporate & Legal/Corporate Structure & Governance', priority: 'Supporting' },
        { id: 'DDI-004', label: 'Capitalization table and ownership records', group: 'input_document', description: 'Current ownership structure, equity distribution, and dilution analysis.', location: 'VDR/Corporate & Legal/Corporate Structure & Governance', priority: 'Critical' },
        { id: 'DDI-005', label: 'Shareholder agreements and voting agreements', group: 'input_document', description: 'Key shareholder rights, restrictions, and control provisions.', location: 'VDR/Corporate & Legal/Corporate Structure & Governance', priority: 'High Prio' },
        { id: 'DDI-008', label: 'Material contracts and agreements', group: 'input_document', description: 'All contracts >$X threshold impacting revenue, costs, or operations.', location: 'VDR/Corporate & Legal/Legal & Compliance', priority: 'Critical' },
        { id: 'DDI-009', label: 'Customer contracts and MSAs', group: 'input_document', description: 'Revenue-generating agreements with key terms and renewal dates.', location: 'VDR/Corporate & Legal/Legal & Compliance', priority: 'Critical' },
        { id: 'DDI-011', label: 'Employment agreements (key personnel)', group: 'input_document', description: 'Contracts for C-suite and key management including terms and restrictions.', location: 'VDR/Corporate & Legal/Legal & Compliance', priority: 'High Prio' },
        { id: 'DDI-013', label: 'Litigation files and court documents', group: 'input_document', description: 'Active, threatened, and historical legal proceedings and disputes.', location: 'VDR/Corporate & Legal/Legal & Compliance', priority: 'High Prio' },
        { id: 'DDI-019', label: 'Patent portfolios and IP registrations', group: 'input_document', description: 'Intellectual property assets, protection scope, and strategic value.', location: 'VDR/Corporate & Legal/Intellectual Property', priority: 'High Prio' },
        { id: 'DDI-025', label: 'Audited financial statements (last 5 years)', group: 'input_document', description: 'Audited P&L, balance sheet, and cash flow statements.', location: 'VDR/Financial/Core Financial Statements', priority: 'Critical' },
        { id: 'DDI-026', label: 'Trial balances and general ledger details', group: 'input_document', description: 'Detailed account-level financial data for verification.', location: 'VDR/Financial/Core Financial Statements', priority: 'High Prio' },
        { id: 'DDI-027', label: 'Management accounts and reporting packages', group: 'input_document', description: 'Internal management reporting and performance metrics.', location: 'VDR/Financial/Core Financial Statements', priority: 'High Prio' },
        { id: 'DDI-029', label: 'Financial models and projections', group: 'input_document', description: 'Forward-looking financial forecasts and scenario analysis.', location: 'VDR/Financial/Financial Analysis & Planning', priority: 'Critical' },
        { id: 'DDI-030', label: 'Capital expenditure budgets and plans', group: 'input_document', description: 'Future investment requirements and capital allocation.', location: 'VDR/Financial/Financial Analysis & Planning', priority: 'High Prio' },
        { id: 'DDI-032', label: 'Working capital schedules', group: 'input_document', description: 'AR, inventory, and AP analysis and cash conversion cycle.', location: 'VDR/Financial/Financial Analysis & Planning', priority: 'High Prio' },
        { id: 'DDI-036', label: 'Accounting policy manual', group: 'input_document', description: 'Accounting principles and policy documentation.', location: 'VDR/Financial/Accounting & Tax', priority: 'High Prio' },
        { id: 'DDI-037', label: 'Revenue recognition policies', group: 'input_document', description: 'Revenue accounting methodology and compliance.', location: 'VDR/Financial/Accounting & Tax', priority: 'High Prio' },
        { id: 'DDI-038', label: 'Management letters from auditors', group: 'input_document', description: 'Auditor recommendations and management responses.', location: 'VDR/Financial/Accounting & Tax', priority: 'High Prio' },
        { id: 'DDI-040', label: 'Tax returns (last 5 years)', group: 'input_document', description: 'Federal and state tax compliance history.', location: 'VDR/Financial/Accounting & Tax', priority: 'High Prio' },
        { id: 'DDI-043', label: 'Expense registers and cost accounting data', group: 'input_document', description: 'Detailed expense categorization and cost allocation.', location: 'VDR/Financial/Cost Structure', priority: 'High Prio' },
        { id: 'DDI-044', label: 'Payroll data and compensation analysis', group: 'input_document', description: 'Employee costs and compensation benchmarking.', location: 'VDR/Financial/Cost Structure', priority: 'High Prio' },
        { id: 'DDI-046', label: 'Cost of goods sold breakdowns', group: 'input_document', description: 'Direct costs and margin analysis by product/service.', location: 'VDR/Financial/Cost Structure', priority: 'High Prio' },
        { id: 'DDI-048', label: 'CRM data and pipeline reports', group: 'input_document', description: 'Sales pipeline quality and conversion metrics.', location: 'VDR/Commercial & Customer/Sales & Marketing', priority: 'Critical' },
        { id: 'DDI-049', label: 'Sales performance and quota attainment data', group: 'input_document', description: 'Individual and team performance against targets.', location: 'VDR/Commercial & Customer/Sales & Marketing', priority: 'Critical' },
        { id: 'DDI-053', label: 'Lead generation and conversion data', group: 'input_document', description: 'Lead quality, sources, and conversion efficiency.', location: 'VDR/Commercial & Customer/Sales & Marketing', priority: 'High Prio' },
        { id: 'DDI-054', label: 'Pricing models and competitive analysis', group: 'input_document', description: 'Pricing strategy and competitive positioning.', location: 'VDR/Commercial & Customer/Sales & Marketing', priority: 'High Prio' },
        { id: 'DDI-056', label: 'Customer transaction databases', group: 'input_document', description: 'Detailed customer purchase history and transaction patterns.', location: 'VDR/Commercial & Customer/Customer Analysis', priority: 'Critical' },
        { id: 'DDI-057', label: 'Billing systems data', group: 'input_document', description: 'Invoice generation, payment terms, and collection data.', location: 'VDR/Commercial & Customer/Customer Analysis', priority: 'Critical' },
        { id: 'DDI-059', label: 'Customer concentration analysis', group: 'input_document', description: 'Revenue dependency on key customers and concentration risk.', location: 'VDR/Commercial & Customer/Customer Analysis', priority: 'Critical' },
        { id: 'DDI-060', label: 'Cohort and retention analysis', group: 'input_document', description: 'Customer behavior patterns and retention trends over time.', location: 'VDR/Commercial & Customer/Customer Analysis', priority: 'High Prio' },
        { id: 'DDI-061', label: 'Churn data and exit interviews', group: 'input_document', description: 'Customer attrition rates, reasons, and prevention strategies.', location: 'VDR/Commercial & Customer/Customer Analysis', priority: 'High Prio' },
        { id: 'DDI-062', label: 'Net Promoter Score surveys', group: 'input_document', description: 'Customer loyalty and satisfaction measurement.', location: 'VDR/Commercial & Customer/Customer Analysis', priority: 'Supporting' },
        { id: 'DDI-065', label: 'Industry reports (Gartner, IDC, etc.)', group: 'input_document', description: 'Third-party market analysis and industry trends.', location: 'VDR/Commercial & Customer/Market Intelligence', priority: 'High Prio' },
        { id: 'DDI-066', label: 'Market research and sizing studies', group: 'input_document', description: 'Market opportunity quantification and growth potential.', location: 'VDR/Commercial & Customer/Market Intelligence', priority: 'High Prio' },
        { id: 'DDI-067', label: 'Competitive intelligence reports', group: 'input_document', description: 'Competitor analysis, strengths, weaknesses, and market share.', location: 'VDR/Commercial & Customer/Market Intelligence', priority: 'High Prio' },
        { id: 'DDI-070', label: 'Product roadmaps and feature backlogs', group: 'input_document', description: 'Future product development priorities and timeline.', location: 'VDR/Technology & Operations/Product & Development', priority: 'High Prio' },
        { id: 'DDI-071', label: 'R&D budgets and resource allocation', group: 'input_document', description: 'Investment in product development and innovation.', location: 'VDR/Technology & Operations/Product & Development', priority: 'High Prio' },
        { id: 'DDI-074', label: 'System architecture diagrams', group: 'input_document', description: 'Technical architecture and system design documentation.', location: 'VDR/Technology & Operations/Technical Infrastructure', priority: 'High Prio' },
        { id: 'DDI-075', label: 'Technology stack documentation', group: 'input_document', description: 'Technology choices, dependencies, and technical specifications.', location: 'VDR/Technology & Operations/Technical Infrastructure', priority: 'High Prio' },
        { id: 'DDI-077', label: 'Security protocols and audit results', group: 'input_document', description: 'Cybersecurity measures, controls, and vulnerability assessments.', location: 'VDR/Technology & Operations/Technical Infrastructure', priority: 'High Prio' },
        { id: 'DDI-087', label: 'Organizational charts and reporting structures', group: 'input_document', description: 'Company hierarchy, reporting relationships, and span of control.', location: 'VDR/Human Resources & Management/Leadership & Organization', priority: 'High Prio' },
        { id: 'DDI-088', label: 'Executive resumes and LinkedIn profiles', group: 'input_document', description: 'Leadership team background, experience, and qualifications.', location: 'VDR/Human Resources & Management/Leadership & Organization', priority: 'High Prio' },
        { id: 'DDI-091', label: 'Compensation plans and structures', group: 'input_document', description: 'Employee compensation philosophy, structure, and pay scales.', location: 'VDR/Human Resources & Management/Compensation & Benefits', priority: 'High Prio' },
        { id: 'DDI-092', label: 'Bonus and incentive programs', group: 'input_document', description: 'Variable compensation design and performance alignment.', location: 'VDR/Human Resources & Management/Compensation & Benefits', priority: 'High Prio' },
        { id: 'DDI-096', label: 'Employee directory and headcount data', group: 'input_document', description: 'Current employee roster and workforce composition.', location: 'VDR/Human Resources & Management/HR Operations', priority: 'High Prio' },
        { id: 'DDI-100', label: 'Turnover and retention data', group: 'input_document', description: 'Employee attrition rates, reasons, and retention strategies.', location: 'VDR/Human Resources & Management/HR Operations', priority: 'High Prio' },
        { id: 'DDI-103', label: 'Strategic plans and presentations', group: 'input_document', description: 'Company strategy, vision, and strategic initiatives.', location: 'VDR/Strategic & Business Development/Strategic Planning', priority: 'Critical' },
        { id: 'DDI-104', label: 'Business plan updates', group: 'input_document', description: 'Current business plan and strategic direction updates.', location: 'VDR/Strategic & Business Development/Strategic Planning', priority: 'High Prio' },
        { id: 'DDI-105', label: 'Investment thesis documentation', group: 'input_document', description: 'PE investment rationale and value creation strategy.', location: 'VDR/Strategic & Business Development/Strategic Planning', priority: 'Critical' },
        { id: 'DDI-107', label: 'Previous acquisition documentation', group: 'input_document', description: 'Historical M&A transactions and deal documentation.', location: 'VDR/Strategic & Business Development/M&A History', priority: 'Supporting' },
        { id: 'DDI-116', label: 'Risk assessment reports', group: 'input_document', description: 'Enterprise risk identification, assessment, and mitigation.', location: 'VDR/Risk & Insurance/Risk Management', priority: 'High Prio' },
        { id: 'DDI-117', label: 'Contingent liability documentation', group: 'input_document', description: 'Potential liabilities and contingent obligations.', location: 'VDR/Risk & Insurance/Risk Management', priority: 'High Prio' },
        { id: 'DDI-120', label: 'Cybersecurity policies and incident reports', group: 'input_document', description: 'Cybersecurity governance and incident management.', location: 'VDR/Risk & Insurance/Risk Management', priority: 'High Prio' },
        { id: 'DDI-121', label: 'Regulatory compliance documentation', group: 'input_document', description: 'Regulatory compliance status and documentation.', location: 'VDR/Risk & Insurance/Regulatory & Compliance', priority: 'High Prio' },
        { id: 'DDI-122', label: 'FCPA compliance policies and procedures', group: 'input_document', description: 'Anti-corruption compliance framework and controls.', location: 'VDR/Corporate & Legal/Legal & Compliance', priority: 'Supporting' },

        // --- GROUP 2: DILIGENCE TASKS (Source: Navigator DD Flow.csv) ---
        { id: 'DD-1', label: 'Company Overview and History', group: 'task', description: 'Company overview with background, founding, mission, and key milestones.', workstream: 'Business & Strategy' },
        { id: 'DD-2', label: 'Organization Review', group: 'task', description: 'Analysis of organizational structure, hierarchy, key roles, and responsibilities.', workstream: 'Business & Strategy' },
        { id: 'DD-3', label: 'Management Assessment', group: 'task', description: 'Evaluation of management team\'s experience, skills, and track record.', workstream: 'Business & Strategy' },
        { id: 'DD-4', label: 'Comp Incentives Analysis', group: 'task', description: 'Review of compensation and incentive structures alignment with company goals.', workstream: 'Business & Strategy' },
        { id: 'DD-5', label: 'HR Growth Plans', group: 'task', description: 'Company\'s talent acquisition and development strategies.', workstream: 'Business & Strategy' },
        { id: 'DD-6', label: 'Acquisition History', group: 'task', description: 'Record of past acquisitions, rationale, integration, and impact.', workstream: 'Business & Strategy' },
        { id: 'DD-7', label: 'Addressable Market', group: 'task', description: 'Total market opportunity estimation and growth potential.', workstream: 'Business & Strategy' },
        { id: 'DD-8', label: 'Barriers to Entry', group: 'task', description: 'Identification of market entry obstacles and competitive moats.', workstream: 'Business & Strategy' },
        { id: 'DD-9', label: 'Macro Trends', group: 'task', description: 'Broader economic, social, and technological trend analysis.', workstream: 'Business & Strategy' },
        { id: 'DD-10', label: 'Competitive Dynamics', group: 'task', description: 'Competitive landscape analysis including key players and strategies.', workstream: 'Business & Strategy' },
        { id: 'DD-11', label: 'Market Positioning', group: 'task', description: 'Company\'s market position relative to competitors.', workstream: 'Business & Strategy' },
        { id: 'DD-12', label: 'Development Process', group: 'task', description: 'Product development lifecycle and methodologies overview.', workstream: 'Technology & Operations' },
        { id: 'DD-13', label: 'Architecture Review', group: 'task', description: 'Technical architecture evaluation including scalability and security.', workstream: 'Technology & Operations' },
        { id: 'DD-14', label: 'Product Roadmap', group: 'task', description: 'Future product development plans and strategic priorities.', workstream: 'Technology & Operations' },
        { id: 'DD-15', label: 'Product Management', group: 'task', description: 'Product development management processes and practices.', workstream: 'Technology & Operations' },
        { id: 'DD-16', label: 'Code Scan', group: 'task', description: 'Codebase quality, security, and maintainability review.', workstream: 'Technology & Operations' },
        { id: 'DD-17', label: 'Documentation', group: 'task', description: 'Product documentation availability and quality assessment.', workstream: 'Technology & Operations' },
        { id: 'DD-18', label: 'QA Testing Review', group: 'task', description: 'Quality assurance and testing processes evaluation.', workstream: 'Technology & Operations' },
        { id: 'DD-19', label: 'Release Management', group: 'task', description: 'Product release management processes examination.', workstream: 'Technology & Operations' },
        { id: 'DD-20', label: 'Pipeline Review', group: 'task', description: 'Sales pipeline analysis including stages and potential revenue.', workstream: 'Commercial & Customer' },
        { id: 'DD-21', label: 'Quota Attainment Analysis', group: 'task', description: 'Sales team performance against quotas review.', workstream: 'Commercial & Customer' },
        { id: 'DD-22', label: 'Turnover Analysis', group: 'task', description: 'Sales team turnover rates and impact examination.', workstream: 'Commercial & Customer' },
        { id: 'DD-23', label: 'Distributors / Channel Partners', group: 'task', description: 'Distributor and channel partner relationships evaluation.', workstream: 'Commercial & Customer' },
        { id: 'DD-24', label: 'Sales Effectiveness', group: 'task', description: 'Sales strategies and tactics effectiveness assessment.', workstream: 'Commercial & Customer' },
        { id: 'DD-25', label: 'Lead Funnel Metrics', group: 'task', description: 'Lead generation and conversion metrics analysis.', workstream: 'Commercial & Customer' },
        { id: 'DD-26', label: 'Conversion Trends', group: 'task', description: 'Sales conversion trends over time examination.', workstream: 'Commercial & Customer' },
        { id: 'DD-27', label: 'Pricing Strategy', group: 'task', description: 'Company\'s pricing strategy and competitive analysis review.', workstream: 'Commercial & Customer' },
        { id: 'DD-28', label: 'Brand Assessment', group: 'task', description: 'Brand strength and perception evaluation.', workstream: 'Commercial & Customer' },
        { id: 'DD-29', label: 'Yield on Sales & Marketing $', group: 'task', description: 'ROI analysis for sales and marketing spend.', workstream: 'Commercial & Customer' },
        { id: 'DD-30', label: 'Detailed Transaction Analysis', group: 'task', description: 'Customer transactions and purchasing behavior review.', workstream: 'Commercial & Customer' },
        { id: 'DD-31', label: 'Cohort Analysis', group: 'task', description: 'Customer cohorts and behavior over time examination.', workstream: 'Commercial & Customer' },
        { id: 'DD-32', label: 'Customer Concentration over time', group: 'task', description: 'Revenue concentration from key customers analysis.', workstream: 'Commercial & Customer' },
        { id: 'DD-33', label: 'Churn Analysis', group: 'task', description: 'Customer churn rates and attrition reasons examination.', workstream: 'Commercial & Customer' },
        { id: 'DD-34', label: 'Net Promoter Score', group: 'task', description: 'Customer satisfaction and loyalty measurement.', workstream: 'Commercial & Customer' },
        { id: 'DD-35', label: 'Lifetime Value', group: 'task', description: 'Customer lifetime value calculation and analysis.', workstream: 'Commercial & Customer' },
        { id: 'DD-36', label: 'Customer Segmentation', group: 'task', description: 'Customer segments identification based on demographics and behavior.', workstream: 'Commercial & Customer' },
        { id: 'DD-37', label: 'Annual Contract Value Trends', group: 'task', description: 'Annual contract values trends analysis.', workstream: 'Commercial & Customer' },
        { id: 'DD-38', label: 'Survey Analysis', group: 'task', description: 'Customer survey results review and insights gathering.', workstream: 'Commercial & Customer' },
        { id: 'DD-39', label: 'Interview w Top Customers', group: 'task', description: 'Top customer interviews for in-depth feedback.', workstream: 'Commercial & Customer' },
        { id: 'DD-40', label: 'Financial Statement Analysis', group: 'task', description: 'Financial statements review including balance sheet and income statement.', workstream: 'Financial & Risk' },
        { id: 'DD-41', label: 'Expense Breakdown', group: 'task', description: 'Company expenses analysis including operating costs and capex.', workstream: 'Financial & Risk' },
        { id: 'DD-42', label: 'Capex Projections', group: 'task', description: 'Future capital expenditures projections.', workstream: 'Financial & Risk' },
        { id: 'DD-43', label: 'Pro-Forma Financial Model', group: 'task', description: 'Pro-forma financial model creation for future performance forecasting.', workstream: 'Financial & Risk' },
        { id: 'DD-44', label: 'Gross Margin Analysis', group: 'task', description: 'Gross margins examination for profitability assessment.', workstream: 'Financial & Risk' },
        { id: 'DD-45', label: 'Growth Assumptions Review', group: 'task', description: 'Growth projections assumptions review and validation.', workstream: 'Financial & Risk' },
        { id: 'DD-46', label: 'Quality of Revenue Analysis', group: 'task', description: 'Revenue quality and sustainability analysis.', workstream: 'Financial & Risk' },
        { id: 'DD-47', label: 'Accounting Policies', group: 'task', description: 'Accounting policies review for compliance and standards.', workstream: 'Financial & Risk' },
        { id: 'DD-48', label: 'Audited Financials', group: 'task', description: 'Audited financial statements examination for accuracy.', workstream: 'Financial & Risk' },
        { id: 'DD-49', label: 'Contingent Liabilities', group: 'task', description: 'Potential contingent liabilities identification.', workstream: 'Financial & Risk' },
        { id: 'DD-50', label: 'Tax Analysis', group: 'task', description: 'Tax situation review including liabilities and compliance.', workstream: 'Financial & Risk' },
        { id: 'DD-51', label: 'Working Capital Review', group: 'task', description: 'Working capital analysis for liquidity and operational efficiency.', workstream: 'Financial & Risk' },
        { id: 'DD-52', label: 'Quality of Earnings', group: 'task', description: 'Earnings quality examination for sustainability and reliability.', workstream: 'Financial & Risk' },
        { id: 'DD-53', label: 'Corporate Documentation Review', group: 'task', description: 'Corporate documents and records review for completeness.', workstream: 'Financial & Risk' },
        { id: 'DD-54', label: 'Patent Analysis', group: 'task', description: 'Patents and intellectual property examination.', workstream: 'Financial & Risk' },
        { id: 'DD-55', label: 'Contract Analysis', group: 'task', description: 'Key contracts and agreements review.', workstream: 'Financial & Risk' },
        { id: 'DD-56', label: 'Litigation Review', group: 'task', description: 'Ongoing and past litigation examination.', workstream: 'Financial & Risk' },
        { id: 'DD-57', label: 'Capitalization Analysis', group: 'task', description: 'Capitalization structure analysis including equity and debt.', workstream: 'Financial & Risk' },
        { id: 'DD-58', label: 'FCPA Audit', group: 'task', description: 'FCPA compliance audit for anti-corruption regulations.', workstream: 'Financial & Risk' },

        // --- GROUP 3: OUTPUT REPORTS (Derived from 'Feeds Into Major Reports' column) ---
        { id: 'report_strat_assess', label: 'Strategic Assessment Report', group: 'output_report', description: 'Synthesizes findings on company strategy, M&A history, and future growth plans.' },
        { id: 'report_mgmt_assess', label: 'Management Assessment Report', group: 'output_report', description: 'Synthesizes findings on leadership, organizational structure, and HR strategy.' },
        { id: 'report_hr_dd', label: 'HR Due Diligence Report', group: 'output_report', description: 'Aggregates analysis of compensation, turnover, and HR growth plans.' },
        { id: 'report_strat_plan_rev', label: 'Strategic Plan Review', group: 'output_report', description: 'Compares company\'s strategic plans against market realities and internal capabilities.' },
        { id: 'report_mkt_assess', label: 'Market Assessment Report', group: 'output_report', description: 'Summarizes market size, competitive dynamics, and macro trends.' },
        { id: 'report_qor', label: 'Quality of Revenue Report', group: 'output_report', description: 'Analyzes the sustainability and quality of the company\'s revenue streams.' },
        { id: 'report_tech_dd', label: 'Technology Due Diligence Report', group: 'output_report', description: 'Assesses the company\'s technology stack, development processes, and product roadmap.' },
        { id: 'report_ops_assess', label: 'Operational Assessment', group: 'output_report', description: 'Evaluates the efficiency and scalability of operational and product management processes.' },
        { id: 'report_risk_assess', label: 'Risk Assessment Report', group: 'output_report', description: 'Identifies and quantifies key business, technology, and legal risks.' },
        { id: 'report_comm_dd', label: 'Commercial Due Diligence Report', group: 'output_report', description: 'Provides a comprehensive view of sales, marketing, and channel effectiveness.' },
        { id: 'report_mkt_eff', label: 'Marketing Effectiveness Report', group: 'output_report', description: 'Focuses on the performance of the marketing funnel and brand strength.' },
        { id: 'report_cust_dd', label: 'Customer Due Diligence Report', group: 'output_report', description: 'Details findings from customer analysis, including churn, LTV, and concentration.' },
        { id: 'report_fin_model_inputs', label: 'Financial Model Inputs', group: 'output_report', description: 'Consolidates all key quantitative findings that drive the pro-forma financial model.' },
        { id: 'report_qoe', label: 'Quality of Earnings Report', group: 'output_report', description: 'Normalizes EBITDA and assesses the target\'s true recurring profitability.' },
        { id: 'report_tax_dd', label: 'Tax Due Diligence Report', group: 'output_report', description: 'Summarizes the company\'s tax compliance, liabilities, and policies.' },
        { id: 'report_legal_dd', label: 'Legal Due Diligence Report', group: 'output_report', description: 'Aggregates findings from all legal workstreams, including contracts, litigation, and corporate structure.' },
        { id: 'report_valuation', label: 'Valuation Analysis', group: 'output_report', description: 'Contains the outputs of financial modeling and growth assumption validation.' },
        { id: 'report_asset_val', label: 'Asset Valuation Report', group: 'output_report', description: 'Specifically details the valuation of intellectual property and other key assets.' },

        // --- GROUP 4: FINAL OUTPUT (The ultimate deliverable) ---
        { id: 'ic_deck', label: 'Investment Committee Deck', group: 'final_output', description: 'Final presentation synthesizing all diligence findings to request capital approval.' }
    ],
    links: [
        // --- CONNECTIONS: Inputs -> Tasks ---
        { source: 'DDI-000', target: 'DD-1' }, { source: 'DDI-000', target: 'DD-53' },
        { source: 'DDI-001', target: 'DD-53' },
        { source: 'DDI-002', target: 'DD-53' },
        { source: 'DDI-004', target: 'DD-57' },
        { source: 'DDI-005', target: 'DD-53' },
        { source: 'DDI-009', target: 'DD-55' },
        { source: 'DDI-013', target: 'DD-56' },
        { source: 'DDI-019', target: 'DD-54' },
        { source: 'DDI-025', target: 'DD-40' }, { source: 'DDI-025', target: 'DD-48' },
        { id: 'DDI-026', target: 'DD-40' },
        { id: 'DDI-027', target: 'DD-40' },
        { source: 'DDI-029', target: 'DD-43' }, { source: 'DDI-029', target: 'DD-45' },
        { source: 'DDI-030', target: 'DD-42' },
        { source: 'DDI-032', target: 'DD-51' },
        { source: 'DDI-036', target: 'DD-47' },
        { source: 'DDI-037', target: 'DD-47' },
        { source: 'DDI-038', target: 'DD-48' },
        { source: 'DDI-040', target: 'DD-50' },
        { source: 'DDI-043', target: 'DD-41' },
        { source: 'DDI-044', target: 'DD-4' },
        { source: 'DDI-046', target: 'DD-44' },
        { source: 'DDI-048', target: 'DD-20' },
        { source: 'DDI-049', target: 'DD-21' },
        { source: 'DDI-053', target: 'DD-25' },
        { source: 'DDI-054', target: 'DD-27' },
        { source: 'DDI-056', target: 'DD-30' },
        { source: 'DDI-057', target: 'DD-30' },
        { source: 'DDI-059', target: 'DD-32' },
        { source: 'DDI-060', target: 'DD-31' },
        { source: 'DDI-061', target: 'DD-33' },
        { source: 'DDI-062', target: 'DD-34' },
        { source: 'DDI-065', target: 'DD-7' },
        { source: 'DDI-066', target: 'DD-7' },
        { source: 'DDI-067', target: 'DD-10' },
        { source: 'DDI-070', target: 'DD-14' },
        { source: 'DDI-071', target: 'DD-14' },
        { source: 'DDI-074', target: 'DD-13' },
        { source: 'DDI-075', target: 'DD-13' },
        { source: 'DDI-077', target: 'DD-13' },
        { source: 'DDI-087', target: 'DD-2' },
        { source: 'DDI-088', target: 'DD-3' },
        { source: 'DDI-091', target: 'DD-4' },
        { source: 'DDI-092', target: 'DD-4' },
        { source: 'DDI-096', target: 'DD-2' },
        { source: 'DDI-100', target: 'DD-22' },
        { source: 'DDI-105', target: 'DD-43' }, { source: 'DDI-105', target: 'DD-45' },
        { source: 'DDI-107', target: 'DD-6' },
        { source: 'DDI-117', target: 'DD-49' },
        { source: 'DDI-122', target: 'DD-58' },

        // --- CONNECTIONS: Task -> Task (Predecessors from DD Flow) ---
        { source: 'DD-1', target: 'DD-2' }, { source: 'DD-1', target: 'DD-3' }, { source: 'DD-1', target: 'DD-6' },
        { source: 'DD-2', target: 'DD-3' }, { source: 'DD-2', target: 'DD-4' }, { source: 'DD-2', target: 'DD-5' },
        { source: 'DD-3', target: 'DD-4' }, { source: 'DD-3', target: 'DD-5' },
        { source: 'DD-4', target: 'DD-5' }, { source: 'DD-4', target: 'DD-22' },
        { source: 'DD-5', target: 'DD-22' },
        { source: 'DD-6', target: 'DD-43' }, { source: 'DD-6', target: 'DD-45' },
        { source: 'DD-7', target: 'DD-8' }, { source: 'DD-7', target: 'DD-9' }, { source: 'DD-7', target: 'DD-10' }, { source: 'DD-7', target: 'DD-11' },
        { source: 'DD-8', target: 'DD-10' }, { source: 'DD-8', target: 'DD-11' },
        { source: 'DD-9', target: 'DD-10' }, { source: 'DD-9', target: 'DD-26' }, { source: 'DD-9', target: 'DD-45' },
        { source: 'DD-10', target: 'DD-11' }, { source: 'DD-10', target: 'DD-27' },
        { source: 'DD-11', target: 'DD-27' }, { source: 'DD-11', target: 'DD-28' },
        { source: 'DD-12', target: 'DD-13' }, { source: 'DD-12', target: 'DD-14' }, { source: 'DD-12', target: 'DD-15' },
        { source: 'DD-13', target: 'DD-16' }, { source: 'DD-13', target: 'DD-17' },
        { source: 'DD-14', target: 'DD-15' }, { source: 'DD-14', target: 'DD-43' },
        { source: 'DD-15', target: 'DD-18' }, { source: 'DD-15', target: 'DD-19' },
        { source: 'DD-16', target: 'DD-17' }, { source: 'DD-16', target: 'DD-18' },
        { source: 'DD-17', target: 'DD-18' },
        { source: 'DD-18', target: 'DD-19' },
        { source: 'DD-20', target: 'DD-21' }, { source: 'DD-20', target: 'DD-24' }, { source: 'DD-20', target: 'DD-29' },
        { source: 'DD-21', target: 'DD-22' }, { source: 'DD-21', target: 'DD-24' },
        { source: 'DD-23', target: 'DD-24' }, { source: 'DD-23', target: 'DD-29' },
        { source: 'DD-24', target: 'DD-29' },
        { source: 'DD-25', target: 'DD-26' }, { source: 'DD-25', target: 'DD-29' },
        { source: 'DD-26', target: 'DD-27' }, { source: 'DD-26', target: 'DD-29' },
        { source: 'DD-27', target: 'DD-44' }, { source: 'DD-27', target: 'DD-46' },
        { source: 'DD-28', target: 'DD-34' }, { source: 'DD-28', target: 'DD-38' },
        { source: 'DD-29', target: 'DD-41' },
        { source: 'DD-30', target: 'DD-31' }, { source: 'DD-30', target: 'DD-32' }, { source: 'DD-30', target: 'DD-35' }, { source: 'DD-30', target: 'DD-37' },
        { source: 'DD-31', target: 'DD-33' }, { source: 'DD-31', target: 'DD-35' }, { source: 'DD-31', target: 'DD-36' },
        { source: 'DD-32', target: 'DD-33' }, { source: 'DD-32', target: 'DD-46' },
        { source: 'DD-33', target: 'DD-34' }, { source: 'DD-33', target: 'DD-35' },
        { source: 'DD-34', target: 'DD-38' }, { source: 'DD-34', target: 'DD-39' },
        { source: 'DD-35', target: 'DD-36' }, { source: 'DD-35', target: 'DD-43' },
        { source: 'DD-36', target: 'DD-38' },
        { source: 'DD-37', target: 'DD-46' }, { source: 'DD-37', target: 'DD-52' },
        { source: 'DD-38', target: 'DD-39' },
        { source: 'DD-40', target: 'DD-41' }, { source: 'DD-40', target: 'DD-44' }, { source: 'DD-40', target: 'DD-46' }, { source: 'DD-40', target: 'DD-48' }, { source: 'DD-40', target: 'DD-51' }, { source: 'DD-40', target: 'DD-52' },
        { source: 'DD-41', target: 'DD-42' }, { source: 'DD-41', target: 'DD-43' }, { source: 'DD-41', target: 'DD-44' },
        { source: 'DD-42', target: 'DD-43' }, { source: 'DD-42', target: 'DD-45' },
        { source: 'DD-43', target: 'DD-45' },
        { source: 'DD-44', target: 'DD-46' }, { source: 'DD-44', target: 'DD-52' },
        { source: 'DD-46', target: 'DD-52' },
        { source: 'DD-47', target: 'DD-48' }, { source: 'DD-47', target: 'DD-50' },
        { source: 'DD-48', target: 'DD-52' },
        { source: 'DD-49', target: 'DD-56' }, { source: 'DD-49', target: 'DD-57' },
        { source: 'DD-50', target: 'DD-51' },
        { source: 'DD-51', target: 'DD-52' },
        { source: 'DD-53', target: 'DD-54' }, { source: 'DD-53', target: 'DD-55' }, { source: 'DD-53', target: 'DD-57' },
        { source: 'DD-54', target: 'DD-55' },
        { source: 'DD-55', target: 'DD-56' },
        { source: 'DD-56', target: 'DD-57' },
        { source: 'DD-57', target: 'DD-58' },

        // --- CONNECTIONS: Tasks -> Reports ---
        { source: 'DD-1', target: 'report_strat_assess' }, { source: 'DD-1', target: 'report_mgmt_assess' },
        { source: 'DD-2', target: 'report_hr_dd' }, { source: 'DD-2', target: 'report_mgmt_assess' },
        { source: 'DD-3', target: 'report_hr_dd' }, { source: 'DD-3', target: 'report_mgmt_assess' },
        { source: 'DD-4', target: 'report_hr_dd' }, { source: 'DD-4', target: 'report_mgmt_assess' },
        { source: 'DD-5', target: 'report_hr_dd' }, { source: 'DD-5', target: 'report_strat_plan_rev' }, { source: 'DD-5', target: 'report_mgmt_assess' },
        { source: 'DD-6', target: 'report_strat_plan_rev' }, { source: 'DD-6', target: 'report_strat_assess' },
        { source: 'DD-7', target: 'report_mkt_assess' }, { source: 'DD-7', target: 'report_qor' },
        { source: 'DD-8', target: 'report_mkt_assess' }, { source: 'DD-8', target: 'report_qor' },
        { source: 'DD-9', target: 'report_mkt_assess' }, { source: 'DD-9', target: 'report_strat_plan_rev' }, { source: 'DD-9', target: 'report_qor' },
        { source: 'DD-10', target: 'report_mkt_assess' }, { source: 'DD-10', target: 'report_qor' },
        { source: 'DD-11', target: 'report_mkt_assess' }, { source: 'DD-11', target: 'report_qor' },
        { source: 'DD-12', target: 'report_tech_dd' }, { source: 'DD-12', target: 'report_ops_assess' }, { source: 'DD-12', target: 'report_risk_assess' },
        { source: 'DD-13', target: 'report_tech_dd' }, { source: 'DD-13', target: 'report_risk_assess' },
        { source: 'DD-14', target: 'report_tech_dd' }, { source: 'DD-14', target: 'report_strat_plan_rev' }, { source: 'DD-14', target: 'report_strat_assess' },
        { source: 'DD-15', target: 'report_tech_dd' }, { source: 'DD-15', target: 'report_ops_assess' }, { source: 'DD-15', target: 'report_risk_assess' },
        { source: 'DD-16', target: 'report_tech_dd' }, { source: 'DD-16', target: 'report_risk_assess' },
        { source: 'DD-17', target: 'report_tech_dd' }, { source: 'DD-17', target: 'report_ops_assess' }, { source: 'DD-17', target: 'report_risk_assess' },
        { source: 'DD-18', target: 'report_tech_dd' }, { source: 'DD-18', target: 'report_ops_assess' }, { source: 'DD-18', target: 'report_risk_assess' },
        { source: 'DD-19', target: 'report_tech_dd' }, { source: 'DD-19', target: 'report_ops_assess' }, { source: 'DD-19', target: 'report_risk_assess' },
        { source: 'DD-20', target: 'report_comm_dd' }, { source: 'DD-20', target: 'report_qor' },
        { source: 'DD-21', target: 'report_comm_dd' }, { source: 'DD-21', target: 'report_qor' },
        { source: 'DD-22', target: 'report_comm_dd' }, { source: 'DD-22', target: 'report_hr_dd' }, { source: 'DD-22', target: 'report_qor' },
        { source: 'DD-23', target: 'report_comm_dd' }, { source: 'DD-23', target: 'report_qor' },
        { source: 'DD-24', target: 'report_comm_dd' }, { source: 'DD-24', target: 'report_qor' },
        { source: 'DD-25', target: 'report_mkt_eff' }, { source: 'DD-25', target: 'report_qor' },
        { source: 'DD-26', target: 'report_mkt_eff' }, { source: 'DD-26', target: 'report_qor' },
        { source: 'DD-27', target: 'report_comm_dd' }, { source: 'DD-27', target: 'report_qor' },
        { source: 'DD-28', target: 'report_mkt_eff' }, { source: 'DD-28', target: 'report_qor' },
        { source: 'DD-29', target: 'report_comm_dd' }, { source: 'DD-29', target: 'report_mkt_eff' }, { source: 'DD-29', target: 'report_qor' },
        { source: 'DD-30', target: 'report_cust_dd' }, { source: 'DD-30', target: 'report_qor' },
        { source: 'DD-31', target: 'report_cust_dd' }, { source: 'DD-31', target: 'report_qor' },
        { source: 'DD-32', target: 'report_cust_dd' }, { source: 'DD-32', target: 'report_risk_assess' },
        { source: 'DD-33', target: 'report_cust_dd' }, { source: 'DD-33', target: 'report_qor' },
        { source: 'DD-34', target: 'report_cust_dd' }, { source: 'DD-34', target: 'report_qor' },
        { source: 'DD-35', target: 'report_cust_dd' }, { source: 'DD-35', target: 'report_fin_model_inputs' },
        { source: 'DD-36', target: 'report_cust_dd' }, { source: 'DD-36', target: 'report_qor' },
        { source: 'DD-37', target: 'report_cust_dd' }, { source: 'DD-37', target: 'report_fin_model_inputs' },
        { source: 'DD-38', target: 'report_cust_dd' }, { source: 'DD-38', target: 'report_qor' },
        { source: 'DD-39', target: 'report_cust_dd' }, { source: 'DD-39', target: 'report_strat_assess' },
        { source: 'DD-40', target: 'report_fin_model_inputs' }, { source: 'DD-40', target: 'report_qoe' },
        { source: 'DD-41', target: 'report_fin_model_inputs' }, { source: 'DD-41', target: 'report_qoe' },
        { source: 'DD-42', target: 'report_fin_model_inputs' }, { source: 'DD-42', target: 'report_strat_plan_rev' }, { source: 'DD-42', target: 'report_strat_assess' },
        { source: 'DD-43', target: 'report_fin_model_inputs' }, { source: 'DD-43', target: 'report_valuation' }, { source: 'DD-43', target: 'report_strat_assess' },
        { source: 'DD-44', target: 'report_fin_model_inputs' }, { source: 'DD-44', target: 'report_qoe' },
        { source: 'DD-45', target: 'report_valuation' }, { source: 'DD-45', target: 'report_risk_assess' },
        { source: 'DD-46', target: 'report_fin_model_inputs' }, { source: 'DD-46', target: 'report_qor' },
        { source: 'DD-47', target: 'report_tax_dd' }, { source: 'DD-47', target: 'report_qoe' },
        { source: 'DD-48', target: 'report_fin_model_inputs' }, { source: 'DD-48', target: 'report_qoe' },
        { source: 'DD-49', target: 'report_legal_dd' }, { source: 'DD-49', target: 'report_risk_assess' },
        { source: 'DD-50', target: 'report_tax_dd' }, { source: 'DD-50', target: 'report_qoe' },
        { source: 'DD-51', target: 'report_fin_model_inputs' }, { source: 'DD-51', target: 'report_qoe' },
        { source: 'DD-52', target: 'report_fin_model_inputs' }, { source: 'DD-52', target: 'report_qoe' },
        { source: 'DD-53', target: 'report_legal_dd' }, { source: 'DD-53', target: 'report_risk_assess' },
        { source: 'DD-54', target: 'report_legal_dd' }, { source: 'DD-54', target: 'report_asset_val' },
        { source: 'DD-55', target: 'report_legal_dd' }, { source: 'DD-55', target: 'report_risk_assess' },
        { source: 'DD-56', target: 'report_legal_dd' }, { source: 'DD-56', target: 'report_risk_assess' },
        { source: 'DD-57', target: 'report_legal_dd' }, { source: 'DD-57', target: 'report_fin_model_inputs' },
        { source: 'DD-58', target: 'report_legal_dd' }, { source: 'DD-58', target: 'report_risk_assess' },

        // --- CONNECTIONS: Reports -> Final Output ---
        { source: 'report_strat_assess', target: 'ic_deck' },
        { source: 'report_mgmt_assess', target: 'ic_deck' },
        { source: 'report_qor', target: 'ic_deck' },
        { source: 'report_risk_assess', target: 'ic_deck' },
        { source: 'report_tech_dd', target: 'ic_deck' },
        { source: 'report_comm_dd', target: 'ic_deck' },
        { source: 'report_fin_model_inputs', target: 'ic_deck' },
        { source: 'report_qoe', target: 'ic_deck' },
        { source: 'report_legal_dd', target: 'ic_deck' },
        { source: 'report_valuation', target: 'ic_deck' }
    ]
};