-- Item_ID: D1
UPDATE Maturity_Rubric
SET
    kpi_name = 'Employee Attrition Rate',
    kpi_description = 'Measures the rate at which employees leave the organization over a given period, calculated as (Employees Who Left / Average Number of Employees) * 100.',
    kpi_rational = 'This is the ultimate lagging indicator of overall organizational health, culture, and leadership effectiveness. A "Reactive" organization with a chaotic culture will have high, unmanaged attrition. As the discipline matures through better talent management ("Organized") and data-driven HR ("Platform-led"), attrition stabilizes. An "Intelligent" organization can predict and prevent attrition, making this the ultimate measure of a successful, sustainable enterprise.',
    alternative_kpis = '• Employee Net Promoter Score (eNPS) <br> • High-Performer Retention Rate <br> • OKR Achievement Rate',
    kpi_formula = '(Number of Employees Who Left / Average Number of Employees) * 100'
WHERE item_id = 'D1';
UPDATE Maturity_Rubric SET kpi_target_value = '> 20%' WHERE item_id = 'D1' AND stage_number = 1;
UPDATE Maturity_Rubric SET kpi_target_value = '15-20%' WHERE item_id = 'D1' AND stage_number = 2;
UPDATE Maturity_Rubric SET kpi_target_value = '10-15%' WHERE item_id = 'D1' AND stage_number = 3;
UPDATE Maturity_Rubric SET kpi_target_value = '5-10%' WHERE item_id = 'D1' AND stage_number = 4;
UPDATE Maturity_Rubric SET kpi_target_value = '< 5%' WHERE item_id = 'D1' AND stage_number = 5;

-- Item_ID: D2
UPDATE Maturity_Rubric
SET
    kpi_name = 'Sales Forecast Accuracy',
    kpi_description = 'Measures the variance between forecasted sales and actual sales results, calculated as 1 - ((|Actual - Forecasted|) / Actual).',
    kpi_rational = 'This KPI measures predictability, the core trait that separates a mature sales function from a "hero-based" art form. A "Reactive" sales team has no reliable forecast. As it matures through defined processes ("Organized") and instrumentation ("Platform-led"), its ability to predict revenue becomes a cornerstone of company-wide strategic planning. An "Intelligent" sales function uses AI to generate highly accurate forecasts, making this the primary indicator of a mature, data-driven science.',
    alternative_kpis = '• Net Revenue Retention (NRR) <br> • Quota Attainment % <br> • Customer Lifetime Value (LTV)',
    kpi_formula = '1 - (|Actual Sales - Forecasted Sales| / Actual Sales)'
WHERE item_id = 'D2';
UPDATE Maturity_Rubric SET kpi_target_value = '< 50%' WHERE item_id = 'D2' AND stage_number = 1;
UPDATE Maturity_Rubric SET kpi_target_value = '50-70%' WHERE item_id = 'D2' AND stage_number = 2;
UPDATE Maturity_Rubric SET kpi_target_value = '70-85%' WHERE item_id = 'D2' AND stage_number = 3;
UPDATE Maturity_Rubric SET kpi_target_value = '85-95%' WHERE item_id = 'D2' AND stage_number = 4;
UPDATE Maturity_Rubric SET kpi_target_value = '> 95%' WHERE item_id = 'D2' AND stage_number = 5;

-- Item_ID: D3
UPDATE Maturity_Rubric
SET
    kpi_name = 'Return on Marketing Investment (ROMI)',
    kpi_description = 'Measures the revenue growth generated by marketing activities as a multiple of the marketing spend, calculated as ((Sales Growth - Marketing Spend) / Marketing Spend).',
    kpi_rational = 'ROMI is the ultimate measure of marketing''s contribution to enterprise value and its evolution from a cost center to a growth engine. A "Reactive" marketing function has untracked spend and negative ROMI. As it matures, it builds a predictable pipeline ("Organized") and can prove its contribution with hard data ("Platform-led"). An "Intelligent" marketing engine uses AI to optimize spend in real-time, maximizing ROMI and solidifying its role as a key driver of corporate strategy.',
    alternative_kpis = '• Marketing Sourced Pipeline ($) <br> • Customer Acquisition Cost (CAC) <br> • Brand Equity Score',
    kpi_formula = '((Sales Growth from Marketing - Marketing Spend) / Marketing Spend) * 100'
WHERE item_id = 'D3';
UPDATE Maturity_Rubric SET kpi_target_value = 'Negative or untracked' WHERE item_id = 'D3' AND stage_number = 1;
UPDATE Maturity_Rubric SET kpi_target_value = '0-2x' WHERE item_id = 'D3' AND stage_number = 2;
UPDATE Maturity_Rubric SET kpi_target_value = '2-4x' WHERE item_id = 'D3' AND stage_number = 3;
UPDATE Maturity_Rubric SET kpi_target_value = '4-7x' WHERE item_id = 'D3' AND stage_number = 4;
UPDATE Maturity_Rubric SET kpi_target_value = '> 7x' WHERE item_id = 'D3' AND stage_number = 5;
